title: Evan Tay
author:
  name: Evan Tay
metadata:
    description: I am a penultimate Computer Science undergraduate who is passionate about full-stack development.

# Header customization
header:
  title: Hello world
  description: I am a penultimate Computer Science undergraduate who is passionate about full-stack development.

copyright:
    - line: Built with Grav, Nginx and DigitalOcean
    - line: &copy; Copyright 2013 - 2019 Evan Tay

social:
- url: "https://www.linkedin.com/in/evanitsg/"
  icon: linkedin
- url: "https://github.com/DigiPie"
  icon: github

redirects:
  /glory: '/#portfolio-glory[303]'
