title: Evan Tay
author:
  name: Evan Tay
metadata:
  description: A Computer Science undergraduate who is passionate about solving meaningful problems as an aspiring Full-stack Software Engineer.

# Header customization
header:
  title: Hello world
  description: I am a Computer Science undergraduate who is passionate about solving meaningful problems as an aspiring Full-stack Software Engineer.

copyright:
  - line: Built with Grav, Nginx and DigitalOcean
  - line: Copyright 2013 - 2020 Evan Tay

social:
  - url: "https://www.linkedin.com/in/evanitsg/"
    icon: linkedin
  - url: "https://github.com/DigiPie"
    icon: github
  - url: "mailto:e0177031@u.nus.edu"
    icon: envelope
  - url: "https://www.evantay.com/docs/"
    icon: file-text

redirects:
  /portfolio: "/#portfolio[303]"
  /digicourse: "/#portfolio-digicourse[303]"
  /dynalite: "/#portfolio-dynalite[303]"
  /braintrain: "/#portfolio-braintrain[303]"
  /glory: "/#portfolio-glory[303]"
  /mongo-action: "/#portfolio-mongo-action[303]"
  /dsc-nus: "/#portfolio-dsc-nus[303]"
  /psql-heroku: "/#portfolio-psql-heroku[303]"
