title: Evan Tay
author:
  name: Evan Tay
metadata:
  description: A Full-stack Software Engineer and Cloud Engineer passionate about solving Meaningful Problems.

# Header customization
header:
  title: Hello world
  description: Hi, I am a Full-stack Software Engineer and Cloud Engineer passionate about solving Meaningful Problems.

copyright:
  - line: Last updated on 15 September 2020

social:
  - url: "https://www.linkedin.com/in/evanitsg/"
    icon: linkedin
    name: LinkedIn
  - url: "https://github.com/DigiPie"
    icon: github
    name: GitHub
  - url: "mailto:evan.it.sg@gmail.com"
    icon: envelope
    name: Email
  - url: "https://github.com/DigiPie/Deedy-Resume/raw/master/resume.pdf"
    icon: file-text
    name: Resume
  - url: "https://www.evantay.com/docs/"
    icon: book
    name: Docs

redirects:
  /portfolio: "/#portfolio[303]"
  /digicourse: "/#portfolio-digicourse[303]"
  /dynalite: "/#portfolio-dynalite[303]"
  /braintrain: "/#portfolio-braintrain[303]"
  /glory: "/#portfolio-glory[303]"
  /mongo-action: "/#portfolio-mongo-action[303]"
  /mochai: "/#portfolio-mochai[303]"
  /dsc-nus: "/#portfolio-dsc-nus[303]"
  /psql-heroku: "/#portfolio-psql-heroku[303]"
