title: Evan Tay
author:
  name: Evan Tay
metadata:
    description: I am a penultimate Computer Science undergraduate and aspiring full-stack developer passionate about solving meaningful problems.

# Header customization
header:
  title: Hello world
  description: I am a penultimate Computer Science undergraduate and aspiring full-stack developer passionate about solving meaningful problems.

copyright:
    - line: Built with Grav, Nginx and DigitalOcean
    - line: &copy; Copyright 2013 - 2019 Evan Tay

social:
- url: "https://www.linkedin.com/in/evanitsg/"
  icon: linkedin
- url: "https://github.com/DigiPie"
  icon: github
- url: "mailto:evantay@comp.nus.edu.sg"
  icon: envelope

redirects:
  /glory: '/#portfolio-glory[303]'
